config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root 'recipes#index'
  get 'pages/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true

  mount_uploader :image, ImageUploader
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end 

	def privacy
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit( :remove_image, :image, :title, :description, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeDb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <%= link_to "RECIPE STASH", root_path, class: 'navbar-brand logo' %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav navbar-right">
      <li><%= link_to "About", pages_about_path %></li>
    </ul>
  </div>
</nav>

  <body>
    <%= yield %>

<script src="https://use.fontawesome.com/0ad4346142.js"></script>
  </body>

</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>

<body>

<div class="container-index">
<h1>Storing recipes is easy with Recipe Stash.</h1>
</div>
	<img src="/about.jpeg" alt="about" class="about-img" />



<div class="gray">
<div class="row">
	<div class="col-md-3">
		<div class="about-step">
		<h2>Step 1</h2>
		<p>Give it a name</p>
		</div>
	</div>

	<div class="col-md-3">
		<div class="about-step">
		<h2>Step 2</h2>
		<p>Add some tasty ingredients</p>
		</div>
	</div>

	<div class="col-md-3">
		<div class="about-step">
		<h2>Step 3</h2>
		<p>Write out some instructions</p>
	</div>
	</div>

	<div class="col-md-3">
		<div class="about-step">
		<h2>Step 4</h2>
		<p>Upload an image</p>
		</div>
	</div>

</div><!--row ends here-->



<br></br>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="gray">
<div class="row">
 
  <div class="col-md-6" style="padding-right: 30px">
  <div class="form-group">
    <h2>Step 1: Name it</h2>
    <%= form.label :title %>
    <%= form.text_field :title, id: :recipe_title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :recipe_description, class: "form-control" %>
  </div>
  </div><!--col ends here-->

<div class="col-md-6">
   <div class="form-group">
    <h2>Step 2: Add tasty ingredients</h2>
 <%= form.nested_fields_for :ingredients do | ingredient|%>
  <%= ingredient.text_field :content%>
  <%= ingredient.remove_nested_fields_link %>
<% end %>
  
  <i class="fa fa-plus"></i>
  <%= form.add_nested_fields_link :ingredients, "Add Ingredient",:class=>"edit_add "%>
</div>
</div>


  
</div><!--row ends here-->

<div class="row">

<div class="col-md-6">
  <div class="form-group">

      <h2>Step 3: Add instructions</h2>
 <%= form.nested_fields_for :steps do | step|%>
  <%= step.text_field :direction%>
  <%= step.remove_nested_fields_link %>
<% end %>
  <i class="fa fa-plus"></i>
  <%= form.add_nested_fields_link :steps, "Add Step",:class=>"edit_add " %>
</div>
</div>

<div class="col-md-6">
   <div class="form-group">
    <h2>Step 4: UPLOAD AN IMAGE</h2>
    <%= form.file_field :image %>
    <% if @recipe.image? %>
      <%= image_tag @recipe.image.url, class: "recipe-show" %>
      <%= form.check_box :remove_image %>
        Remove Image
    <% end %>
    </div>
  </div><!--col ends here-->
</div><!--row ends here-->
</div>
<br></br>

  <div class="actions">
    <%= form.submit "Add Recipe", :class=>"btn-info btn-submit"%>
  </div>

<% end %>

app/views/recipes/edit.html.erb
<div class="container container-index">
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<br></br>
<button type="button" class="btn btn-danger">
<%= link_to 'Cancel', @recipe %>
</button>

<button type="button" class="btn btn-secondary">
<%= link_to 'Back to all recipes', recipes_path %>
</button>
<br></br>
</div>

app/views/recipes/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="row">
    <% @recipes.each do |recipe| %>
    <div class="col-md-4">
    <div class="recipe-box">
      <% if recipe.image? %>
        <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
      <%end%>
        <ul>
        <li><%= recipe.title %></li>
        <li><%= recipe.description %></li>
        <li><%= link_to 'Show', recipe %> |
        <%= link_to 'Edit', edit_recipe_path(recipe) %> |
        <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
    </div><!--col-md-4-->
    <% end %>
    <div class="col-md-4 col_last">
<div class="new-recipe">
<div class="row">
<%= link_to 'New Recipe', new_recipe_path %>
</div> <!--row here-->
<div class="row">
<i class="fa fa-plus fa-3x icon"></i>
</div>
</div>
</div>
<div><!--/row-->
<br>

app/views/recipes/new.html.erb
<div class="container container-form">

<h1>Create a New Recipe</h1>
<br></br>
<%= render 'form', recipe: @recipe %>

<br></br>
<button type="button" class="btn btn-danger">
<%= link_to 'Cancel', recipes_path %>
</button>

<br></br>
</div>

app/views/recipes/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<% if @recipe.image? %>
	<%= image_tag @recipe.image.url, class: "recipe-show" %>
<% end %>
<h1>
  <%= @recipe.title %>
</h1>

<p>
  <%= @recipe.description %>
</p>

<div class="row">
 <div class="col-md-6 ingredients">
 <div class="ingredients-box">

	<h3>Ingredients</h3>
		<% for @ingredient in @recipe.ingredients %>
		<ul>
			<li><%= @ingredient.content %></li>
		</ul>
		<% end %>
</div>
</div>

<div class="col-md-6 steps">
	 <div class="steps-box">
<h3>Steps</h3>
	<ol>
	<% for @step in @recipe.steps %>
		<li><%= @step.direction %></li>
	<% end %>
	</ol>
</div>
</div>

</div>
<button type="button" class="btn btn-info">
<%= link_to 'Edit Recipe', edit_recipe_path(@recipe) %>
</button>
<button type="button" class="btn btn-secondary">
<%= link_to 'Back', recipes_path %>
</button>
</div>
<br></br>